# Generated by Django 3.1.3 on 2020-11-20 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackaton_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, verbose_name='Group name')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, verbose_name='Role')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hackaton_app.profile')),
                ('user_group', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hackaton_app.usergroup')),
            ],
        ),
        migrations.CreateModel(
            name='FlashcardSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_hash', models.CharField(max_length=6, verbose_name='Validation hash')),
                ('host', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hackaton_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.BooleanField()),
                ('question', models.CharField(max_length=300, verbose_name='Question')),
                ('is_abcd', models.BooleanField()),
                ('a', models.CharField(max_length=50, verbose_name='Option a')),
                ('b', models.CharField(max_length=50, verbose_name='Option b')),
                ('c', models.CharField(max_length=50, verbose_name='LOption c')),
                ('d', models.CharField(max_length=50, verbose_name='Option d')),
                ('correct_answer', models.CharField(max_length=300, verbose_name='Correct answer')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hackaton_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerFlashcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=300, verbose_name='Answer')),
                ('flash_card', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hackaton_app.flashcard')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hackaton_app.profile')),
            ],
        ),
    ]
