# Generated by Django 3.1.3 on 2020-11-20 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackaton_app', '0002_answerflashcard_flashcard_flashcardsession_membership_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='a',
            field=models.CharField(default=0, max_length=50, verbose_name='Option a'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='b',
            field=models.CharField(default=0, max_length=50, verbose_name='Option b'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='c',
            field=models.CharField(default=0, max_length=50, verbose_name='LOption c'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='correct_answer',
            field=models.CharField(default=0, max_length=300, verbose_name='Correct answer'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='d',
            field=models.CharField(default=0, max_length=50, verbose_name='Option d'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackaton_app.profile'),
        ),
    ]
