# Generated by Django 3.1.3 on 2020-11-21 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackaton_app', '0003_auto_20201121_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='is_abcd',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AssignedFlashcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField(auto_now=True)),
                ('flash_card', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hackaton_app.flashcard')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hackaton_app.profile')),
            ],
        ),
    ]
