# Generated by Django 3.1.3 on 2020-11-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackaton_app', '0005_flashcard_is_openquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='abcd_answer',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], default='a', max_length=1),
        ),
    ]
