# Generated by Django 3.1.3 on 2020-11-21 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hackaton_app', '0006_flashcard_abcd_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedflashcard',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
